"use client";

import { useI18n } from "@/contexts/i18n-context";
import { FaqAccordion, FaqItem } from "@/components/docs/faq-accordion";
import { HelpCircle, Key, CreditCard, Cpu, Settings, Plug } from "lucide-react";

/* ------------------------------------------------------------------ */
/*  Category definitions                                               */
/* ------------------------------------------------------------------ */

const categories = [
  {
    icon: Key,
    anchor: "account-keys",
    titleEn: "Account & Keys",
    titleZh: "账户与密钥",
    items: [
      {
        id: "get-api-key",
        questionEn: "How do I get an API Key?",
        questionZh: "如何获取 API Key？",
        answerEn: (
          <>
            <p>Register an account, go to the Dashboard, navigate to <strong>API Keys</strong>, and click <strong>Create</strong>. Your key will start with <code className="px-1.5 py-0.5 rounded bg-muted text-foreground text-xs">sk-oort-</code>.</p>
          </>
        ),
        answerZh: (
          <>
            <p>注册账户后，进入控制台，导航至 <strong>API Keys</strong> 页面，点击 <strong>创建</strong>。生成的密钥以 <code className="px-1.5 py-0.5 rounded bg-muted text-foreground text-xs">sk-oort-</code> 开头。</p>
          </>
        ),
      },
      {
        id: "lost-api-key",
        questionEn: "I lost my API Key, what do I do?",
        questionZh: "API Key 丢失了怎么办？",
        answerEn: (
          <>
            <p>Go to Dashboard &rarr; <strong>API Keys</strong>, delete the compromised key, and create a new one. Update your applications with the new key immediately.</p>
          </>
        ),
        answerZh: (
          <>
            <p>进入控制台 &rarr; <strong>API Keys</strong>，删除已泄露的密钥，然后创建一个新的。请立即更新所有使用旧密钥的应用。</p>
          </>
        ),
      },
      {
        id: "multiple-api-keys",
        questionEn: "Can I create multiple API Keys?",
        questionZh: "可以创建多个 API Key 吗？",
        answerEn: (
          <>
            <p>Yes. You can create multiple API Keys, each with its own rate limit and permissions. This is useful for separating different projects or environments.</p>
          </>
        ),
        answerZh: (
          <>
            <p>可以。您可以创建多个 API Key，每个密钥可以设置不同的速率限制和权限。这对于区分不同项目或环境非常有用。</p>
          </>
        ),
      },
    ],
  },
  {
    icon: CreditCard,
    anchor: "billing",
    titleEn: "Billing",
    titleZh: "计费",
    items: [
      {
        id: "billing-model",
        questionEn: "How does billing work?",
        questionZh: "计费方式是怎样的？",
        answerEn: (
          <>
            <p>OortAPI uses a <strong>pay-per-token</strong> model. Each model has different rates. Your balance is deducted per request based on the number of tokens consumed. Check the <a href="/docs/pricing" className="text-primary underline underline-offset-2">Pricing page</a> for detailed rates.</p>
          </>
        ),
        answerZh: (
          <>
            <p>OortAPI 采用<strong>按量计费</strong>模式。不同模型有不同的费率，每次请求根据消耗的 Token 数量扣费。请查看<a href="/docs/pricing" className="text-primary underline underline-offset-2">定价页面</a>了解详细费率。</p>
          </>
        ),
      },
      {
        id: "token-types",
        questionEn: "What are the different token types?",
        questionZh: "Token 类型有哪些？",
        answerEn: (
          <>
            <p>There are four token types:</p>
            <ul className="list-disc pl-5 mt-2 space-y-1">
              <li><strong>Input tokens</strong> — tokens sent in your request</li>
              <li><strong>Completion tokens</strong> — tokens generated by the model</li>
              <li><strong>Cache read tokens</strong> — tokens read from the prompt cache (cheaper)</li>
              <li><strong>Cache create tokens</strong> — tokens used to create cache entries</li>
            </ul>
          </>
        ),
        answerZh: (
          <>
            <p>共有四种 Token 类型：</p>
            <ul className="list-disc pl-5 mt-2 space-y-1">
              <li><strong>输入 Token</strong> — 请求中发送的 Token</li>
              <li><strong>输出 Token</strong> — 模型生成的 Token</li>
              <li><strong>缓存读取 Token</strong> — 从提示缓存中读取的 Token（价格更低）</li>
              <li><strong>缓存写入 Token</strong> — 用于创建缓存条目的 Token</li>
            </ul>
          </>
        ),
      },
      {
        id: "balance-exhausted",
        questionEn: "What happens when my balance runs out?",
        questionZh: "余额用完会怎样？",
        answerEn: (
          <>
            <p>The API returns <code className="px-1.5 py-0.5 rounded bg-muted text-foreground text-xs">402 Payment Required</code>. Top up your balance in Dashboard &rarr; <strong>Billing</strong> to resume usage.</p>
          </>
        ),
        answerZh: (
          <>
            <p>API 将返回 <code className="px-1.5 py-0.5 rounded bg-muted text-foreground text-xs">402 Payment Required</code> 错误。请在控制台 &rarr; <strong>账单</strong> 中充值以恢复使用。</p>
          </>
        ),
      },
      {
        id: "check-balance",
        questionEn: "How do I check my balance?",
        questionZh: "如何查看余额？",
        answerEn: (
          <>
            <p>You can check your balance by calling the API endpoint:</p>
            <pre className="mt-2 rounded-lg bg-muted p-3 text-xs overflow-x-auto"><code>GET /api/v1/billing/balance</code></pre>
            <p className="mt-2">Or simply view it in the Dashboard under the <strong>Billing</strong> section.</p>
          </>
        ),
        answerZh: (
          <>
            <p>您可以通过调用 API 接口查看余额：</p>
            <pre className="mt-2 rounded-lg bg-muted p-3 text-xs overflow-x-auto"><code>GET /api/v1/billing/balance</code></pre>
            <p className="mt-2">或者直接在控制台的<strong>账单</strong>页面查看。</p>
          </>
        ),
      },
    ],
  },
  {
    icon: Cpu,
    anchor: "models",
    titleEn: "Models",
    titleZh: "模型",
    items: [
      {
        id: "available-models",
        questionEn: "Which models are available?",
        questionZh: "有哪些可用模型？",
        answerEn: (
          <>
            <p>Call the models endpoint for the full, up-to-date list:</p>
            <pre className="mt-2 rounded-lg bg-muted p-3 text-xs overflow-x-auto"><code>GET /api/v1/models</code></pre>
            <p className="mt-2">Available models include GPT-4o, Claude (Sonnet/Opus/Haiku), Gemini, DeepSeek, Qwen, and more.</p>
          </>
        ),
        answerZh: (
          <>
            <p>调用模型接口获取完整的最新列表：</p>
            <pre className="mt-2 rounded-lg bg-muted p-3 text-xs overflow-x-auto"><code>GET /api/v1/models</code></pre>
            <p className="mt-2">可用模型包括 GPT-4o、Claude（Sonnet/Opus/Haiku）、Gemini、DeepSeek、Qwen 等。</p>
          </>
        ),
      },
      {
        id: "choose-model",
        questionEn: "How do I choose the right model?",
        questionZh: "如何选择合适的模型？",
        answerEn: (
          <>
            <p>Use <strong>GPT-4o</strong> or <strong>Claude Sonnet</strong> for complex reasoning, coding, and creative tasks. For simpler or cost-sensitive tasks, smaller models like GPT-4o-mini or Haiku work well. Check the <a href="/docs/pricing" className="text-primary underline underline-offset-2">Pricing page</a> for cost comparisons.</p>
          </>
        ),
        answerZh: (
          <>
            <p>对于复杂的推理、编程和创意任务，推荐使用 <strong>GPT-4o</strong> 或 <strong>Claude Sonnet</strong>。对于简单或对成本敏感的任务，较小的模型如 GPT-4o-mini 或 Haiku 就足够了。请查看<a href="/docs/pricing" className="text-primary underline underline-offset-2">定价页面</a>了解成本对比。</p>
          </>
        ),
      },
    ],
  },
  {
    icon: Settings,
    anchor: "technical",
    titleEn: "Technical",
    titleZh: "技术",
    items: [
      {
        id: "rate-limits",
        questionEn: "What are the rate limits?",
        questionZh: "速率限制是多少？",
        answerEn: (
          <>
            <p>The default rate limit is <strong>60 requests per minute (RPM)</strong> per API key. You can adjust it from 1 to 10,000 RPM in Dashboard &rarr; <strong>API Keys</strong>.</p>
          </>
        ),
        answerZh: (
          <>
            <p>默认速率为每个 API Key <strong>每分钟 60 次请求（RPM）</strong>。您可以在控制台 &rarr; <strong>API Keys</strong> 中将其调整为 1 到 10,000 RPM。</p>
          </>
        ),
      },
      {
        id: "streaming",
        questionEn: "Do you support streaming?",
        questionZh: "支持流式输出吗？",
        answerEn: (
          <>
            <p>Yes. Both <strong>OpenAI SSE</strong> and <strong>Anthropic SSE</strong> formats are supported. Simply set <code className="px-1.5 py-0.5 rounded bg-muted text-foreground text-xs">stream: true</code> in your request body.</p>
          </>
        ),
        answerZh: (
          <>
            <p>支持。<strong>OpenAI SSE</strong> 和 <strong>Anthropic SSE</strong> 两种格式均支持。只需在请求体中设置 <code className="px-1.5 py-0.5 rounded bg-muted text-foreground text-xs">stream: true</code> 即可。</p>
          </>
        ),
      },
      {
        id: "error-handling",
        questionEn: "How do I handle errors?",
        questionZh: "如何处理错误？",
        answerEn: (
          <>
            <p>Check the <a href="/docs/errors" className="text-primary underline underline-offset-2">Error Codes page</a> for a full list. For transient errors like <code className="px-1.5 py-0.5 rounded bg-muted text-foreground text-xs">429</code>, <code className="px-1.5 py-0.5 rounded bg-muted text-foreground text-xs">500</code>, and <code className="px-1.5 py-0.5 rounded bg-muted text-foreground text-xs">502</code>, use <strong>exponential backoff</strong> to retry your requests.</p>
          </>
        ),
        answerZh: (
          <>
            <p>请查看<a href="/docs/errors" className="text-primary underline underline-offset-2">错误码页面</a>了解完整列表。对于 <code className="px-1.5 py-0.5 rounded bg-muted text-foreground text-xs">429</code>、<code className="px-1.5 py-0.5 rounded bg-muted text-foreground text-xs">500</code> 和 <code className="px-1.5 py-0.5 rounded bg-muted text-foreground text-xs">502</code> 等临时性错误，建议使用<strong>指数退避</strong>策略重试请求。</p>
          </>
        ),
      },
    ],
  },
  {
    icon: Plug,
    anchor: "integration",
    titleEn: "Integration",
    titleZh: "集成",
    items: [
      {
        id: "base-url",
        questionEn: "What is the Base URL?",
        questionZh: "Base URL 是什么？",
        answerEn: (
          <>
            <p>The Base URLs are:</p>
            <ul className="list-disc pl-5 mt-2 space-y-1">
              <li><strong>OpenAI compatible:</strong> <code className="px-1.5 py-0.5 rounded bg-muted text-foreground text-xs">{"{your-domain}/api/v1"}</code></li>
              <li><strong>Anthropic compatible:</strong> <code className="px-1.5 py-0.5 rounded bg-muted text-foreground text-xs">{"{your-domain}/api"}</code></li>
            </ul>
            <p className="mt-2">Both endpoints use the same API Key.</p>
          </>
        ),
        answerZh: (
          <>
            <p>Base URL 如下：</p>
            <ul className="list-disc pl-5 mt-2 space-y-1">
              <li><strong>OpenAI 兼容：</strong><code className="px-1.5 py-0.5 rounded bg-muted text-foreground text-xs">{"{your-domain}/api/v1"}</code></li>
              <li><strong>Anthropic 兼容：</strong><code className="px-1.5 py-0.5 rounded bg-muted text-foreground text-xs">{"{your-domain}/api"}</code></li>
            </ul>
            <p className="mt-2">两个端点使用相同的 API Key。</p>
          </>
        ),
      },
      {
        id: "supported-clients",
        questionEn: "Which clients are supported?",
        questionZh: "支持哪些客户端？",
        answerEn: (
          <>
            <p>OortAPI supports a wide range of clients: <strong>ChatBox</strong>, <strong>Cherry Studio</strong>, <strong>Open WebUI</strong>, <strong>NextChat</strong>, <strong>LobeChat</strong>, <strong>Claude Code</strong>, and any OpenAI-compatible client.</p>
          </>
        ),
        answerZh: (
          <>
            <p>OortAPI 支持多种客户端：<strong>ChatBox</strong>、<strong>Cherry Studio</strong>、<strong>Open WebUI</strong>、<strong>NextChat</strong>、<strong>LobeChat</strong>、<strong>Claude Code</strong>，以及任何兼容 OpenAI 的客户端。</p>
          </>
        ),
      },
      {
        id: "openai-sdk",
        questionEn: "Can I use the OpenAI SDK?",
        questionZh: "可以使用 OpenAI SDK 吗？",
        answerEn: (
          <>
            <p>Yes! Just change the <code className="px-1.5 py-0.5 rounded bg-muted text-foreground text-xs">base_url</code> to your OortAPI endpoint. The same applies to the Anthropic SDK — point it to your OortAPI Anthropic-compatible endpoint.</p>
          </>
        ),
        answerZh: (
          <>
            <p>可以！只需将 <code className="px-1.5 py-0.5 rounded bg-muted text-foreground text-xs">base_url</code> 改为您的 OortAPI 端点即可。Anthropic SDK 同理 — 将其指向您的 OortAPI Anthropic 兼容端点。</p>
          </>
        ),
      },
    ],
  },
];

/* ------------------------------------------------------------------ */
/*  Page component                                                     */
/* ------------------------------------------------------------------ */

export default function FaqPage() {
  const { lang } = useI18n();

  return (
    <div className="space-y-10">
      {/* Page heading */}
      <div>
        <div className="flex items-center gap-2 mb-2">
          <HelpCircle className="h-6 w-6 text-primary" />
          <h1 className="text-2xl font-bold tracking-tight">
            {lang === "zh" ? "常见问题" : "FAQ"}
          </h1>
        </div>
        <p className="text-muted-foreground">
          {lang === "zh"
            ? "OortAPI 常见问题解答"
            : "Common questions and answers about OortAPI"}
        </p>
      </div>

      {/* FAQ categories */}
      {categories.map((cat) => {
        const Icon = cat.icon;
        return (
          <section key={cat.anchor} id={cat.anchor} className="space-y-4">
            <div className="flex items-center gap-2">
              <Icon className="h-5 w-5 text-primary" />
              <h2 className="text-lg font-semibold">
                {lang === "zh" ? cat.titleZh : cat.titleEn}
              </h2>
            </div>

            <FaqAccordion single>
              {cat.items.map((item) => (
                <FaqItem
                  key={item.id}
                  id={item.id}
                  question={lang === "zh" ? item.questionZh : item.questionEn}
                >
                  {lang === "zh" ? item.answerZh : item.answerEn}
                </FaqItem>
              ))}
            </FaqAccordion>
          </section>
        );
      })}
    </div>
  );
}
